services:
  blackjack:
    image: dgoldstein1/blackjack:0.0.2
    ports:
      - 8080:8080
    environment:
      - MONGO_HOST=mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0.6
    ports:
      - 27017:27017
      
